import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import QueryClientProvider from '@/providers/query-client-provider'

const geistSans = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'CRM - Vai na Web',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.className} bg-[#F5F5FA] antialiased overflow-hidden`}
      >
        <QueryClientProvider>
          <Toaster richColors />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
